default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: eventpay_manager_development

test:
  <<: *default
  database: eventpay_manager_test

production:
  <<: *default
  database: eventpay_manager_production
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
